version: '3.9'

services:
  web:
    build:
      context: GOTemplate
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8000:8000"
    command: "./main"

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_storage:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_storage:
